import type { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar"
import { SidebarProvider } from "@/components/ui/sidebar"
import { ThemeProvider } from "@/components/providers/theme-provider";
import LoginPanel from "@/components/login-panel";
import { getCurrentUser } from "@/database/actions/users-actions";
import { ReactNode } from "react";
import { ClientAppContextProvider } from "@/providers/app-context-provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const user = await getCurrentUser();

  if (!user) {
    return (
      <html lang="en">
        <body className={`h-screen w-screen antialiased dark`}>
          <LoginPanel />
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={`h-screen w-screen antialiased dark`}>
        <ThemeProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-full h-full">
              <ClientAppContextProvider user={user}>
                {children}
              </ClientAppContextProvider>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
